dist: focal
language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - python3 -m pip install -U pip setuptools wheel
  - python3 -m pip install pipx
  - pipx install poetry==1.7.0
  - poetry install
# command to run tests
script:
  - poetry run python3 tests.py
